services:
  smn-api:
    image: miqueiasbto/smn-arquitetura:staging
    ports:
      - "8080:8080"
    container_name: smn-api
    environment:
      SPRING_PROFILES_ACTIVE: staging
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ROOT_EMAIL: ${ROOT_EMAIL}
      ROOT_USERNAME: ${ROOT_USERNAME}
      ROOT_PASSWORD: ${ROOT_PASSWORD}
      AWS_QUEUE_NAME: ${AWS_QUEUE_NAME}
      AWS_QUEUE_URL: ${AWS_QUEUE_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
      - pgadmin
    networks:
      - smn-network


  postgres:
    image: postgres:17-alpine
    container_name: postgres-smn-staging
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata-staging:/var/lib/postgresql/data
    networks:
      - smn-network

  pgadmin:
    image: dpage/pgadmin4:9.7.0
    container_name: pgadmin-smn-staging
    ports:
      - "5050:80"
    env_file:
    - env/.env.staging
    depends_on:
      - postgres
    networks:
      - smn-network

networks:
  smn-network:
    driver: bridge

volumes:
  pgdata-staging:
    driver: local
  pgadmindata-staging:
    driver: local
