services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-smn-dev
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    networks:
      - smn-network

  pgadmin:
    image: dpage/pgadmin4:9.7.0
    container_name: pgadmin-smn-dev
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmindata-dev:/var/lib/pgadmin/data
    depends_on:
      - postgres
    networks:
      - smn-network

networks:
  smn-network:
    driver: bridge

volumes:
  pgdata-dev:
    driver: local
  pgadmindata-dev:
    driver: local
